load('ext://ko', 'ko_build')
ko_build(
  'frnn4268/k8s-api-golang', 
  './',
  deps=['.']
)
k8s_yaml('../../k8s_3-tier_webapp_deployment/api-golang/Deployment.yaml')
k8s_resource('api-golang', port_forwards=8000)